image: debian:jessie

cache:
  paths:
  - vendor/

before_script:
- echo '10.14.129.44 svn.unicaen.fr' >> /etc/hosts # Pour passer par l'intranet
# Mise à niveau de la distrib et installation des packages requis
- echo 'deb http://debian.unicaen.fr/debian/ jessie main non-free contrib' > /etc/apt/sources.list
- apt-get -qq update && apt-get -qq install -y wget php5-cli php5-gd php5-curl git subversion
- echo "http_proxy = $HTTP_PROXY" >> /etc/wgetrc
- echo "https_proxy = $HTTPS_PROXY" >> /etc/wgetrc
# Téléchargement de composer.phar
- wget -q https://composer.github.io/installer.sig
- wget -q https://getcomposer.org/installer && mv installer composer-setup.php
- php -r "if (hash_file('SHA384', 'composer-setup.php') != trim(file_get_contents('installer.sig'))) { echo 'Installer corrupted.' . PHP_EOL; unlink('composer-setup.php'); exit(1); }"
- php composer-setup.php --quiet
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
# Installation des dépendances de l'appli
- php composer.phar install --no-interaction # NB: La variable d'env COMPOSER_AUTH doit être renseignée

test:filters:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml module/Application/tests/ApplicationUnitTest/Filter

test:rules:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml module/Application/tests/ApplicationUnitTest/Rule
