stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_preprod:
  stage: deploy
  script:
    - git push "$DEPLOY_USER:$DEPLOY_PASSWORD"@sygal-pp.unicaen.fr:/var/www/sygal.git master
  when: manual
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - master

