image: localhost:5000/unicaen-dev-php7.0-apache
  
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"
  only:
  - master

build:
  stage: build
  script: echo "Building the app"
  only:
  - master

deploy_preprod:
  stage: deploy
  script:
    - git push root@usygalpp1.unr-runn.fr:/var/www/sygal.git master
  when: manual
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
  - master

