version: '2'

services:
  sygal:
    container_name: sygal-container
    build:
      context: .
    ports:
     - "8000:80"
     - "443:443"
    volumes:
     - .:/var/www/sygal
     - /tmp:/tmp
    working_dir: /var/www/sygal

  sygal-import-ws:
    container_name: sygal-import-ws-container
    build:
      context: ../sygal-import-ws
    ports:
     - "8080:80"
     - "8443:443"
    volumes:
     - ../sygal-import-ws:/var/www/sygal-import-ws
    working_dir: /var/www/sygal-import-ws
