version: '2'
services:
  sygal:
    build:
      context: .
      dockerfile: Dockerfile.php7.dev
      args:
        http_proxy: http://10.14.128.99:3128
        https_proxy: http://10.14.128.99:3128
        no_proxy: localhost,.unicaen.fr
    ports:
     - "8000:80"
    volumes:
     - .:/webapp
    container_name: sygal-container
#    dns: 10.14.128.125
#    dns_search: unicaen.fr